export const CREATE_HOUSE = 'CREATE_HOUSE';
export const DELETE_HOUSE = 'DELETE_HOUSE';

export const REQUEST_HOUSES_PENDING = 'REQUEST_HOUSES_PENDING';
export const REQUEST_HOUSES_SUCCESS = 'REQUEST_HOUSES_SUCCESSG';
export const REQUEST_HOUSES_FAILED = 'REQUEST_HOUSES_FAILED';
